# Generated by Django 4.2 on 2023-04-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TUSER', 'T_user'), ('VIPUSER', 'VIP_user')], default='TUSER', max_length=50),
        ),
    ]
