# Generated by Django 4.2.1 on 2023-11-15 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0008_remove_authtoken_salt'),
        ('core', '0003_remove_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatKey',
            fields=[
                ('authtoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knox.authtoken')),
            ],
            bases=('knox.authtoken',),
        ),
    ]
