# Generated by Django 4.2.1 on 2024-01-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_confirmation_code_user_confirmation_tries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirmation_tries',
        ),
        migrations.RemoveField(
            model_name='user',
            name='next_confirm_try',
        ),
        migrations.RemoveField(
            model_name='user',
            name='next_confirmation_code_sent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='resend_tries',
        ),
    ]
