# Generated by Django 4.2.1 on 2023-11-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_alter_conversation_room_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='room_name',
            field=models.UUIDField(),
        ),
    ]
