# Generated by Django 4.2.1 on 2023-11-11 11:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_alter_conversation_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='room_name',
        ),
        migrations.AddField(
            model_name='conversation',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_set', to='conversation.conversation'),
        ),
    ]
